services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quran-app
    ports:
      - "4000:4000"
    restart: unless-stopped
    command: gunicorn --workers 4 --bind 0.0.0.0:4000 app:app

